<#compress>
[{ 
	"action":"${extdirectjResponse.action}"
	,"method":"${extdirectjResponse.method}"
	,"result":"${extdirectjResponse.result}"
	,"type":"${extdirectjResponse.type}"
	,"tid":${extdirectjResponse.tid}
 }]
 </#compress>