<#compress>
[{ 
	'action':'${extdirectjResponse.action}'
	,'method':'${extdirectjResponse.method}'
	,'result':'${extdirectjResponse.result}'
	,'type':'exception'
	,'tid':${extdirectjResponse.tid}
	,'where':'${extdirectjResponse.where}'
	,'message':'${extdirectjResponse.message}'
 }]
 </#compress>